apiVersion: v1
kind: ReplicationController
metadata:
  name: tomcat-controller
spec:
  replicas: 3
  selector:
    app: frontend
  template:
    metadata:
      name: tomcat-controller
      labels:
        app: frontend
    spec:
      containers:
        - name: tomcat-controller
          image: dheenathayalanb/vprofileapp
          ports:
            - containerPort: 8080
